#!/usr/bin/env python3
"""Install global entrypoints to a reconciled, repo-backed AGENTS.md."""
from __future__ import annotations

import argparse
from datetime import datetime, timezone
import hashlib
import json
import os
from pathlib import Path
import shutil
import tempfile

from repository_registry import load_registry, render_overview


GENERATED_MARKER = "<!-- Generated by SkillPort bootstrap-agent-guidance.py. Do not edit. -->"


def _atomic_write(destination: Path, content: str) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    handle, temporary_name = tempfile.mkstemp(prefix=f".{destination.name}.", dir=destination.parent)
    temporary = Path(temporary_name)
    try:
        with os.fdopen(handle, "w", encoding="utf-8", newline="\n") as stream:
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, destination)
    finally:
        temporary.unlink(missing_ok=True)


def _apply_plans(plans: list[tuple[Path, str, bool, bool]], replace: bool,
                 dry_run: bool, protected_sources: set[Path]) -> None:
    pending = []
    for destination, content, link, managed in plans:
        resolved_destination = destination.resolve() if destination.exists() else destination.absolute()
        if resolved_destination in protected_sources:
            if link and destination.is_symlink():
                continue
            raise ValueError(f"Destination must not overwrite source: {destination}")
        exists = destination.exists() or destination.is_symlink()
        if destination.is_dir():
            raise ValueError(f"Expected a file, found a directory: {destination}")
        if exists and not link and not destination.is_symlink():
            if destination.read_text(encoding="utf-8") == content:
                continue
        generated = exists and not destination.is_symlink() and destination.read_text(
            encoding="utf-8", errors="replace"
        ).startswith(GENERATED_MARKER)
        if exists and not replace and not (managed and generated):
            raise ValueError(f"Reconcile existing preferences before --replace-existing: {destination}")
        pending.append((destination, content, link, exists, generated))

    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S%fZ")
    for destination, content, link, exists, generated in pending:
        print(f"{'Would install' if dry_run else 'Install'} {'symlink' if link else 'generated/reference'}: {destination}")
        if dry_run:
            continue
        destination.parent.mkdir(parents=True, exist_ok=True)
        if exists:
            if not generated:
                backup = destination.parent / "guidance-backups" / stamp / destination.name
                backup.parent.mkdir(parents=True, exist_ok=True)
                if destination.is_symlink():
                    _atomic_write(backup, destination.read_text(encoding="utf-8"))
                else:
                    shutil.copy2(destination, backup)
            destination.unlink()
        if link:
            destination.symlink_to(next(iter(protected_sources)))
        else:
            _atomic_write(destination, content)
        assert destination.read_text(encoding="utf-8") == (
            next(iter(protected_sources)).read_text(encoding="utf-8") if link else content
        )


def install(source: Path, codex_home: Path, claude_home: Path,
            replace: bool = False, dry_run: bool = False,
            opencode_home: Path | None = None) -> None:
    source = source.resolve(strict=True)
    if not source.is_file() or not source.read_text(encoding="utf-8").strip():
        raise ValueError("Source must be a nonempty UTF-8 guidance file")
    codex = codex_home / "AGENTS.md"
    claude = claude_home / "CLAUDE.md"
    override = codex_home / "AGENTS.override.md"
    if override.exists() and override.read_text(encoding="utf-8").strip():
        raise ValueError(f"Reconcile the overriding global guidance first: {override}")
    wrapper = ("Before responding or taking action, read the complete shared personal "
               f"instructions at `{source.as_posix()}` and follow them for this task. "
               "If the file cannot be read, report the missing source. "
               "Edit that repository source when updating these rules, not this wrapper.\n")
    # Claude treats the remainder of a one-line import as the path, including
    # spaces. Codex uses a symlink and OpenCode stores a JSON string.
    imports = f"@{source.as_posix()}\n"
    plans = [(codex, wrapper, os.name != "nt"), (claude, imports, False)]
    if opencode_home is not None:
        config = opencode_home / "opencode.json"
        if (opencode_home / "opencode.jsonc").exists():
            raise ValueError("Reconcile existing OpenCode JSONC before bootstrapping")
        data = json.loads(config.read_text(encoding="utf-8")) if config.exists() else {}
        instructions = data.get("instructions", [])
        if not isinstance(instructions, list) or not all(isinstance(p, str) for p in instructions):
            raise ValueError("OpenCode instructions must be an array of paths")
        if source.as_posix() not in instructions:
            data["instructions"] = [*instructions, source.as_posix()]
        data.setdefault("$schema", "https://opencode.ai/config.json")
        plans.append((config, json.dumps(data, indent=2) + "\n", False))
    _apply_plans([(path, content, link, False) for path, content, link in plans],
                 replace, dry_run, {source})


def install_layered(common: Path, overlay: Path, platform: str, codex_home: Path,
                    claude_home: Path, replace: bool = False,
                    dry_run: bool = False, opencode_home: Path | None = None,
                    registry: Path | None = None) -> None:
    common = common.resolve(strict=True)
    overlay = overlay.resolve(strict=True)
    if common == overlay:
        raise ValueError("Common guidance and platform overlay must be different files")
    for source in (common, overlay):
        if not source.is_file() or not source.read_text(encoding="utf-8").strip():
            raise ValueError("Each guidance layer must be a nonempty UTF-8 file")
    if not platform or any(character in platform for character in "\r\n<>"):
        raise ValueError("Platform label is invalid")

    common_text = common.read_text(encoding="utf-8").strip()
    overlay_text = overlay.read_text(encoding="utf-8").strip()
    overview = ""
    protected_sources = {common, overlay}
    if registry is not None:
        registry = registry.resolve(strict=True)
        overview = "\n\n" + render_overview(load_registry(registry))
        protected_sources.add(registry)
    digest = hashlib.sha256((common_text + "\0" + overlay_text + overview).encode()).hexdigest()[:16]
    rendered = (
        f"{GENERATED_MARKER}\n"
        f"<!-- Platform: {platform}; source digest: {digest} -->\n\n"
        "# Global agent guidance\n\n"
        "This file is generated atomically from the canonical common rules and this "
        "machine's platform overlay. Edit those private repository sources, not this file.\n\n"
        f"{common_text}\n\n{overlay_text}{overview}\n"
    )
    codex = codex_home / "AGENTS.md"
    claude = claude_home / "CLAUDE.md"
    override = codex_home / "AGENTS.override.md"
    if override.exists() and override.read_text(encoding="utf-8").strip():
        raise ValueError(f"Reconcile the overriding global guidance first: {override}")

    imports = f"@{common.as_posix()}\n@{overlay.as_posix()}\n"
    plans: list[tuple[Path, str, bool, bool]] = [
        (codex, rendered, False, True),
        (claude, imports, False, False),
    ]
    if opencode_home is not None:
        config = opencode_home / "opencode.json"
        if (opencode_home / "opencode.jsonc").exists():
            raise ValueError("Reconcile existing OpenCode JSONC before bootstrapping")
        data = json.loads(config.read_text(encoding="utf-8")) if config.exists() else {}
        instructions = data.get("instructions", [])
        if not isinstance(instructions, list) or not all(isinstance(path, str) for path in instructions):
            raise ValueError("OpenCode instructions must be an array of paths")
        legacy = (common.parent / "AGENTS.md").resolve(strict=False).as_posix()
        retained = [path for path in instructions if path not in {legacy, common.as_posix(), overlay.as_posix()}]
        data["instructions"] = [*retained, common.as_posix(), overlay.as_posix()]
        data.setdefault("$schema", "https://opencode.ai/config.json")
        plans.append((config, json.dumps(data, indent=2) + "\n", False, False))
    _apply_plans(plans, replace, dry_run, protected_sources)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--source", type=Path)
    mode.add_argument("--common", type=Path)
    parser.add_argument("--overlay", type=Path)
    parser.add_argument("--platform")
    parser.add_argument("--registry", type=Path)
    parser.add_argument("--codex-home", type=Path, default=Path(os.environ.get("CODEX_HOME", Path.home() / ".codex")))
    parser.add_argument("--claude-home", type=Path, default=Path.home() / ".claude")
    parser.add_argument("--opencode-home", type=Path, default=Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config")) / "opencode")
    parser.add_argument("--replace-existing", action="store_true", help="Only after merging old preferences; originals are backed up")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()
    if args.source:
        if args.overlay or args.platform or args.registry:
            parser.error("--overlay, --platform and --registry require --common")
        install(args.source, args.codex_home, args.claude_home, args.replace_existing, args.dry_run, args.opencode_home)
    else:
        if not args.overlay or not args.platform:
            parser.error("--common requires --overlay and --platform")
        install_layered(args.common, args.overlay, args.platform, args.codex_home,
                        args.claude_home, args.replace_existing, args.dry_run,
                        args.opencode_home, args.registry)


if __name__ == "__main__":
    main()
